namespace SQLFundamentals.DataAccess.Controllers
{
    public class OrderController
    {
        // TO DO
        // - METHODS FOR GET BY ID, GET ALL, CREATE, UPDATE, DELETE
        // - USE SYSTEM.DATA.SQLCLIENT, OLD SCHOOL, LOWEST LEVEL
        // - THIS IS FOR POTENTIAL STUDENTS
        // - DO THIS ON THE ORDERS TABLE IN THE SQL FUNDAMENTALS DATABASE
        
        // THIS IS A SAMPLE CODE PROJECT FOR STUDENTS SO DON'T DO ANYTHING FANCY - KEEP IT SIMPLE
        
        // FOR THE METHOD PARAMETER STRATEGY - JUST TAKE THEM ALL IN LIKE THIS FOR EXAMPLE: CreateContact(string firstName, string lastName, ...)
        
        // USE PARAMETER BASED STRATEGY TO BUILD THE SQL STRINGS
        // DO NOT, DON'T DO, THIS: sql = "INSERT INTO ... VALUES(' + firstName ')
        // YOU SHOULD DDO THIS: sql = "INSERT INTO ... VALUES(@FIRSTNAME)
        // THEN USE THE COMMAND OBJECT AND DO ADD WITH PARAMETER VALUE OR WHATEVER IT'S CALLED
        
        // FOR THE QUERIES, THAT'S WHEN YOU WOULD USE THE ORDER MODEL
        
        // DO A CONSOLE APP WITH OPTIONS LIKE 1 - PRESS 1 TO CREATE A CONTACT
        // THEN MAYBE PROMPT THEM TO SAY, PRESS 1 TO ENTER THE CONTACT'S DETAILS OR PRESS 2 TO INSERT A CONTACT WITH THE DEFAULT DATA
    }
}